/**
 * Fresh Harvest — catalog-depth store (ADR-2.8-010).
 *
 * Fruit and vegetables are where the pack-based rule (ADR-2.8-004) does the
 * most work: "Tomatoes 500 g" and "Tomatoes 1 kg" are separate Products with
 * separate SKUs and separate stock counts. Nothing here needs a unit of
 * measure, a price-per-kg, or a fractional quantity.
 *
 * This store also exercises `brandId: null` heavily — loose produce genuinely
 * has no brand, and the catalog model has always allowed that (catalog 7).
 */

import type { CatalogStoreSeed } from "./types";

const CAT_VEGETABLES = "produce_cat_vegetables";
const CAT_FRUITS = "produce_cat_fruits";
const CAT_HERBS = "produce_cat_herbs";

const SUB_SEASONAL = "produce_sub_seasonal";
const SUB_IMPORTED = "produce_sub_imported";

const BRAND_HARVEST_SELECT = "produce_brand_harvest_select";

export const produceStore: CatalogStoreSeed = {
  key: "produce",

  merchant: {
    id: "produce_merchant_devraj",
    email: "devraj.shinde@freshharvest.test",
    name: "Devraj Shinde",
  },

  store: {
    id: "produce_store_fresh",
    name: "Fresh Harvest",
    slug: "fresh-harvest",
    defaultLowStockThreshold: 15,
  },

  brands: [
    // Only the packed, graded lines carry a brand. Loose produce does not.
    { id: BRAND_HARVEST_SELECT, name: "Harvest Select", slug: "harvest-select" },
  ],

  categories: [
    { id: CAT_VEGETABLES, name: "Vegetables", slug: "vegetables", position: 0 },
    { id: CAT_FRUITS, name: "Fruits", slug: "fruits", position: 1 },
    { id: CAT_HERBS, name: "Herbs & Greens", slug: "herbs-greens", position: 2 },
  ],

  subcategories: [
    { id: SUB_SEASONAL, categoryId: CAT_FRUITS, name: "Seasonal", slug: "seasonal", position: 0 },
    { id: SUB_IMPORTED, categoryId: CAT_FRUITS, name: "Imported", slug: "imported", position: 1 },
  ],

  products: [
    {
      id: "produce_prod_tomato_500",
      name: "Tomatoes 500 g",
      slug: "tomatoes-500g",
      sku: "FH-VEG-TOM-500",
      description: "Firm salad tomatoes, hand-graded, 500 g pack.",
      lifecycleStatus: "ACTIVE",
      brandId: null,
      categoryId: CAT_VEGETABLES,
      subcategoryId: null,
      mrpPaise: 2400,
      sellingPricePaise: 2400,
      costPricePaise: 1700,
      stockQuantity: 120,
      lowStockThreshold: 30,
      specs: { netWeightGrams: 500, origin: "Nashik", organic: false, shelfLifeDays: 5 },
      imageAlt: "Pack of 500 grams of salad tomatoes",
    },
    {
      // Different pack, different Product, different SKU (ADR-2.8-004).
      id: "produce_prod_tomato_1kg",
      name: "Tomatoes 1 kg",
      slug: "tomatoes-1kg",
      sku: "FH-VEG-TOM-1000",
      description: "Firm salad tomatoes, hand-graded, 1 kg pack.",
      lifecycleStatus: "ACTIVE",
      brandId: null,
      categoryId: CAT_VEGETABLES,
      subcategoryId: null,
      mrpPaise: 4500,
      sellingPricePaise: 4200,
      costPricePaise: 3200,
      stockQuantity: 74,
      lowStockThreshold: 20,
      specs: { netWeightGrams: 1000, origin: "Nashik", organic: false, shelfLifeDays: 5 },
      imageAlt: "Pack of 1 kilogram of salad tomatoes",
    },
    {
      id: "produce_prod_onion_1kg",
      name: "Onions 1 kg",
      slug: "onions-1kg",
      sku: "FH-VEG-ONI-1000",
      description: "Medium red onions, 1 kg pack.",
      lifecycleStatus: "ACTIVE",
      brandId: null,
      categoryId: CAT_VEGETABLES,
      subcategoryId: null,
      mrpPaise: 3800,
      sellingPricePaise: 3800,
      costPricePaise: 2900,
      stockQuantity: 156,
      lowStockThreshold: 40,
      specs: { netWeightGrams: 1000, origin: "Nashik", organic: false, shelfLifeDays: 21 },
      imageAlt: "Pack of 1 kilogram of red onions",
    },
    {
      id: "produce_prod_potato_1kg",
      name: "Potatoes 1 kg",
      slug: "potatoes-1kg",
      sku: "FH-VEG-POT-1000",
      description: "All-purpose potatoes, washed and graded, 1 kg pack.",
      lifecycleStatus: "ACTIVE",
      brandId: null,
      categoryId: CAT_VEGETABLES,
      subcategoryId: null,
      mrpPaise: 3200,
      sellingPricePaise: 3000,
      costPricePaise: 2200,
      stockQuantity: 143,
      lowStockThreshold: 40,
      specs: { netWeightGrams: 1000, origin: "Indore", organic: false, shelfLifeDays: 30 },
      imageAlt: "Pack of 1 kilogram of washed potatoes",
    },
    {
      id: "produce_prod_capsicum_250",
      name: "Green Capsicum 250 g",
      slug: "green-capsicum-250g",
      sku: "FH-VEG-CAP-250",
      description: "Crisp green capsicum, 250 g pack.",
      lifecycleStatus: "ACTIVE",
      brandId: null,
      categoryId: CAT_VEGETABLES,
      subcategoryId: null,
      mrpPaise: 2800,
      sellingPricePaise: 2800,
      costPricePaise: 2050,
      stockQuantity: 11,
      lowStockThreshold: 25,
      specs: { netWeightGrams: 250, origin: "Pune", organic: false, shelfLifeDays: 7 },
      imageAlt: "Pack of 250 grams of green capsicum",
    },
    {
      id: "produce_prod_spinach_200",
      name: "Harvest Select Baby Spinach 200 g",
      slug: "harvest-select-baby-spinach-200g",
      sku: "FH-HRB-SPN-200",
      description: "Washed, ready-to-cook baby spinach in a 200 g sealed pack.",
      lifecycleStatus: "ACTIVE",
      brandId: BRAND_HARVEST_SELECT,
      categoryId: CAT_HERBS,
      subcategoryId: null,
      mrpPaise: 3500,
      sellingPricePaise: 3200,
      costPricePaise: 2400,
      stockQuantity: 47,
      lowStockThreshold: null,
      specs: { netWeightGrams: 200, origin: "Pune", washed: true, shelfLifeDays: 4 },
      imageAlt: "Sealed 200 gram pack of washed baby spinach",
    },
    {
      id: "produce_prod_coriander_100",
      name: "Coriander 100 g",
      slug: "coriander-100g",
      sku: "FH-HRB-COR-100",
      description: "Fresh coriander bunch, roughly 100 g.",
      lifecycleStatus: "ACTIVE",
      brandId: null,
      categoryId: CAT_HERBS,
      subcategoryId: null,
      mrpPaise: 1500,
      sellingPricePaise: 1500,
      costPricePaise: 900,
      stockQuantity: 88,
      lowStockThreshold: null,
      specs: { netWeightGrams: 100, origin: "Pune", washed: false, shelfLifeDays: 3 },
      imageAlt: "Fresh coriander bunch of about 100 grams",
    },
    {
      id: "produce_prod_mint_100",
      name: "Mint Leaves 100 g",
      slug: "mint-leaves-100g",
      sku: "FH-HRB-MNT-100",
      description: "Fresh mint bunch, roughly 100 g.",
      lifecycleStatus: "ACTIVE",
      brandId: null,
      categoryId: CAT_HERBS,
      subcategoryId: null,
      mrpPaise: 1400,
      sellingPricePaise: 1400,
      costPricePaise: 850,
      stockQuantity: 0,
      lowStockThreshold: null,
      specs: { netWeightGrams: 100, origin: "Pune", washed: false, shelfLifeDays: 3 },
      imageAlt: "Fresh mint bunch of about 100 grams",
    },
    {
      id: "produce_prod_banana_6",
      name: "Bananas 6 pcs",
      slug: "bananas-6-pcs",
      sku: "FH-FRT-BAN-6",
      description: "Robusta bananas, six to a pack, picked slightly under-ripe.",
      lifecycleStatus: "ACTIVE",
      brandId: null,
      categoryId: CAT_FRUITS,
      subcategoryId: SUB_SEASONAL,
      mrpPaise: 4200,
      sellingPricePaise: 4200,
      costPricePaise: 3100,
      stockQuantity: 95,
      lowStockThreshold: 25,
      specs: { pieceCount: 6, origin: "Theni", organic: false, shelfLifeDays: 6 },
      imageAlt: "Pack of six robusta bananas",
    },
    {
      id: "produce_prod_mango_1kg",
      name: "Alphonso Mangoes 1 kg",
      slug: "alphonso-mangoes-1kg",
      sku: "FH-FRT-MNG-1000",
      description: "Ratnagiri Alphonso mangoes, roughly four to a 1 kg box.",
      lifecycleStatus: "ACTIVE",
      brandId: BRAND_HARVEST_SELECT,
      categoryId: CAT_FRUITS,
      subcategoryId: SUB_SEASONAL,
      mrpPaise: 48000,
      sellingPricePaise: 44000,
      // Premium seasonal line the merchant buys on consignment; cost unknown.
      costPricePaise: null,
      stockQuantity: 18,
      lowStockThreshold: 10,
      specs: { netWeightGrams: 1000, origin: "Ratnagiri", organic: false, shelfLifeDays: 6 },
      imageAlt: "One kilogram box of Ratnagiri Alphonso mangoes",
    },
    {
      id: "produce_prod_pomegranate_500",
      name: "Pomegranate 500 g",
      slug: "pomegranate-500g",
      sku: "FH-FRT-POM-500",
      description: "Deep-red pomegranate, roughly one large fruit per 500 g pack.",
      lifecycleStatus: "ACTIVE",
      brandId: null,
      categoryId: CAT_FRUITS,
      subcategoryId: SUB_SEASONAL,
      mrpPaise: 12000,
      sellingPricePaise: 11000,
      costPricePaise: 8400,
      stockQuantity: 62,
      lowStockThreshold: null,
      specs: { netWeightGrams: 500, origin: "Solapur", organic: false, shelfLifeDays: 12 },
      imageAlt: "Pack of 500 grams of deep red pomegranate",
    },
    {
      id: "produce_prod_kiwi_3",
      name: "Imported Kiwi 3 pcs",
      slug: "imported-kiwi-3-pcs",
      sku: "FH-FRT-KWI-3",
      description: "Green kiwi, three to a pack, imported.",
      lifecycleStatus: "ACTIVE",
      brandId: BRAND_HARVEST_SELECT,
      categoryId: CAT_FRUITS,
      subcategoryId: SUB_IMPORTED,
      mrpPaise: 11000,
      sellingPricePaise: 10500,
      costPricePaise: 8600,
      stockQuantity: 34,
      lowStockThreshold: null,
      specs: { pieceCount: 3, origin: "New Zealand", organic: false, shelfLifeDays: 14 },
      imageAlt: "Pack of three imported green kiwi fruit",
    },
    {
      id: "produce_prod_avocado_2",
      name: "Imported Avocado 2 pcs",
      slug: "imported-avocado-2-pcs",
      sku: "FH-FRT-AVO-2",
      description: "Hass avocado, two to a pack. Line discontinued after poor sell-through.",
      // ARCHIVED: withdrawn from sale, record retained (ADR-2.7-004, PRD-16).
      lifecycleStatus: "ARCHIVED",
      brandId: BRAND_HARVEST_SELECT,
      categoryId: CAT_FRUITS,
      subcategoryId: SUB_IMPORTED,
      mrpPaise: 26000,
      sellingPricePaise: 24000,
      costPricePaise: 21000,
      stockQuantity: 0,
      lowStockThreshold: null,
      specs: { pieceCount: 2, origin: "Peru", organic: false, shelfLifeDays: 8 },
      imageAlt: "Pack of two imported Hass avocados",
    },
  ],

  customers: [
    {
      id: "produce_cust_nandini",
      email: "nandini.rao@example.test",
      name: "Nandini Rao",
      phone: "+919820011223",
    },
    {
      id: "produce_cust_joseph",
      email: "joseph.mathew@example.test",
      name: "Joseph Mathew",
      phone: null,
    },
  ],

  sessions: [
    {
      id: "produce_sess_nandini_1",
      anonymousId: "produce-anon-nandini-4a8de210",
      customerId: "produce_cust_nandini",
      day: 1,
      minutes: 20,
      durationMinutes: 11,
    },
    {
      id: "produce_sess_joseph_1",
      anonymousId: "produce-anon-joseph-b3197fcd",
      customerId: "produce_cust_joseph",
      day: 5,
      minutes: 75,
      durationMinutes: 7,
    },
  ],

  orders: [
    {
      id: "produce_order_nandini_1",
      customerId: "produce_cust_nandini",
      sessionId: "produce_sess_nandini_1",
      idempotencyKey: "produce-checkout-nandini-0001",
      day: 1,
      minutes: 29,
      lines: [
        { productId: "produce_prod_tomato_1kg", quantity: 1 },
        { productId: "produce_prod_onion_1kg", quantity: 1 },
        { productId: "produce_prod_coriander_100", quantity: 2 },
        { productId: "produce_prod_banana_6", quantity: 1 },
      ],
      providerOrderId: "order_FHNandini0001",
      providerPaymentId: "pay_FHNandini0001",
    },
    {
      id: "produce_order_joseph_1",
      customerId: "produce_cust_joseph",
      sessionId: "produce_sess_joseph_1",
      idempotencyKey: "produce-checkout-joseph-0001",
      day: 5,
      minutes: 81,
      lines: [
        { productId: "produce_prod_mango_1kg", quantity: 1 },
        { productId: "produce_prod_spinach_200", quantity: 2 },
      ],
      providerOrderId: "order_FHJoseph0001",
      providerPaymentId: "pay_FHJoseph0001",
    },
  ],
};
